on:
  release:
    types:  [published]

jobs:
  publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          ref: ${{ github.ref }}
      - name: publish release
        run: |
          npm install
          npm run build
          npm run publish-amo
    env:
      AMO_JWT_ISS: ${{ secrets.AMO_JWT_ISS }}
      AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
