on:
  release:
    types:  [published]

jobs:
  publish:
    runs-on:  ubuntu-latest
    steps:
      - name: publish release
        run: |
          npm install
          npm run build
          npm run publish-webstore
    env:
      WEBSTORE_CLIENT_ID: ${{ secret.WEBSTORE_CLIENT_ID }}
      WEBSTORE_CLIENT_SECRET: ${{ secret.WEBSTORE_CLIENT_ID }}
      WEBSTORE_REFRESH_TOKEN: ${{ secret.WEBSTORE_REFRESH_TOKEN }}